### DISCUSSION TITLE
Synology, Portenier, Docker Mumble Setup

### DISCUSSION THREAD

**Discussion by wliporace** [mumble-voip/mumble-docker#31] [Q&A]
I'm not sure where to start! I'm VERY new to mumble, Synology & Docker.  I've got absolutely no idea (sort of) what I'm doing. I have portainer installed on my Synology DS918+. I was able to get RustDesk to work. I just followed one of the online instructions and no issues that I know of so far! 

Recently I was introduced to mumble. It should be a great answer to what I would like to do (mostly have ham radio audio get passed, duplex). I know there are lots of threads to do this on a raspberry pi. Yea, I have a couple that I could use. I thought the Synology NAS would be a better option!! 

If I specify what I think is the right path to my NAS, I get:
 /entrypoint.sh: line 77: /data/mumble_server_config.ini: Permission denied in the logs for the container. 
If I let the system create the container/stack from mumblevoip/mumble-server, no issues. 
The problem is that I have NO idea on how or where to edit things. I tried and the terminal told me that there is NO editor and I don't have any option to install one. 

Anyone that can help would be awesome! I need a little training and understanding of how this works. The good news, my works schedule got better with the weather coming in!

**Comment by Krzmbrzl** [comment]
You'll have to provide more detail on how exactly you are starting up the Docker service. Otherwise, all we can do is to guess.

**Reply by wliporace** [reply]
Here is my docker compose 
```
version: '3'
services:
  mumble-server:
        image: mumblevoip/mumble-server
        container_name: mumble-server
        hostname: mumble-server
		restart: on-failure
        ports: 
          - 64738:64738
          - 64738:64738/udp

        volumes:
          - /volume1/docker/mumble/server:/data
        depends_on:
          - postgres

  mumble-mumo:
        image: mumblevoip/mumo:latest
        container_name: mumble-mumo
        restart: on-failure
        volumes:
            - /volume1/docker/mumble/mumo:/data
        network_mode : "service:mumble-server"
        depends_on:
            - mumble-server

  postgres:
        image: postgres:14
        container_name: postgres
        hostname: postgres
        restart: on-failure
        expose:
            - 5432
        volumes:
            - /volume1/docker/mumble/postgres/data:/var/lib/postgresql/
```
My Files look like:
![image](https://user-images.githubusercontent.com/121176813/224683999-56267d91-1376-4624-86db-71d8da53b746.png)

**Reply by Krzmbrzl** [reply]
So the line the error is coming from is
https://github.com/mumble-voip/mumble-docker/blob/f113629123f868288528f36b6a65d4405230771d/entrypoint.sh#L77
which together with the provided error message means that there is a file permission error at hand that doesn't allow you to write to the config file, which is located at `/data/mumble_server_config.ini` within your Mumble server container.
From your compose file, it seems like you are trying to share the same volume it seems like you are binding an explicit volume to this path. However, I don't know enough about this compose business to fully understand where that path would refer to on your local filesystem. Maybe @azlux can help?

A suggestion I can already make is that you should check https://github.com/mumble-voip/mumble-docker/tree/master#requirements - in particular the note about the `mumble` user and its UID and GID. You have to ensure that a user with these properties can create new files in the local directory that you are binding the `/data` directory to. For testing purposes, this could be achieved simply by allowing `other` write access inside your directory.

**Reply by wliporace** [reply]
Thank you.  Sorry for asking, you were so quick to reply the first time. 

If I just let the mumblevoip/mumble-server image run, it installs just fine. It of course does not use the path/locations that I would prefer. I don't know how to enter/edit any of the files that it creates (if allowed).  
When I try to set environment variables in the docker compose, it doesn't seem to like it (my issue). It may be the syntax or something that I am missing. 
I have no idea on what user needs to be set in docker. I thought that the user (me) installing, it would allow me to set it.  

If I need to download all of the files and do my own install/build, I have NO idea on how to do this. I appreciate ANY help!

**Reply by Krzmbrzl** [reply]
We have a (probably) working example available at https://github.com/mumble-voip/mumble-docker/wiki/docker_example_mumble_mumo_postgres, which should be rather close to what you are trying to achieve. Maybe that helps?

**Reply by wliporace** [reply]
That is what I was trying to figure out..  
So, I noticed that the mumble-server does not define a volume. Does it need to reside in a default location??
So does the system define the usernames/passwords? How/where do I define them? 

So here is what I just tried.. 
version: "3"
services:
    mumble-server:
        image: mumblevoip/mumble-server:latest
        container_name: mumble-server
        hostname: mumble-server
        restart: on-failure
        environment:
            MUMBLE_CONFIG_DATABASE: mumble
            MUMBLE_CONFIG_DB_DRIVER: QPSQL
            MUMBLE_CONFIG_DB_USERNAME: wc2l  
            MUMBLE_CONFIG_DB_PASSWORD: JustadummyPassw0rd!
            MUMBLE_CONFIG_DB_HOST: postgres
            MUMBLE_CONFIG_DB_PORT: 5432
            MUMBLE_CONFIG_ICE: tcp -h 127.0.0.1 -p 6502
            MUMBLE_CONFIG_IMAGEMESSAGELENGTH: 1310720
            MUMBLE_CONFIG_REGISTERNAME: Main Channel Name
            MUMBLE_CONFIG_USERNAME: '[ -=\\w\\[\\]\\{\\}\\(\\)\\@\\|\\.]+'
            MUMBLE_CONFIG_CHANNELNAME: '[ \\-=\\w\\#\\[\\]\\{\\}\\(\\)\\@\\|\\%\\'']+'
            MUMBLE_CONFIG_WELCOMETEXT: 'Hello there !'
            MUMBLE_VERBOSE: 1
        ports:
            - 64738:64738
            - 64738:64738/udp
        depends_on:
            - postgres

    mumble-mumo:
        image: mumblevoip/mumo
        container_name: mumble-mumo
        restart: on-failure
        volumes:
            - ../volume1/docker/mumble/mumo:/data
        network_mode : "service:mumble-server"
        depends_on:
            - mumble-server

    postgres:
        image: postgres:14
        container_name: postgres
        hostname: postgres
        restart: on-failure
        expose:
            - 5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: JustadummyPassw0rd!
        volumes:
            - ../volume1/docker/mumble/postgres/data:/var/lib/postgresql/data

I get this error:
failed to deploy a stack: Network mumble-server_default Creating Network mumble-server_default Created Container postgres Creating Container postgres Created Container mumble-server Creating Container mumble-server Created Container mumble-mumo Creating Container mumble-mumo Created Container postgres Starting Error response from daemon: Bind mount failed: '/data/compose/volume1/docker/mumble/postgres/data' does not exists
![image](https://user-images.githubusercontent.com/121176813/225093216-0ee87ca4-6995-469f-9ea6-9b63da793c47.png)

If I define a volume under mumble-server
        volumes:
            - ../volume1/docker/mumble
I get this error:
failed to deploy a stack: Network mumble-server_default Creating Network mumble-server_default Created Container postgres Creating Container postgres Created Container mumble-server Creating Error response from daemon: invalid mount config for type "volume": invalid mount path: '../volume1/docker/mumble' mount path must be absolute

**Reply by Krzmbrzl** [reply]
@azlux :point_up:

**Reply by azlux** [reply]
Hi,
The mumbler-server use UID 1000 by default. So you need to fix the rights on your folder on your host, or mumble cannot write files here)
You can observe that if you run your docker with `docker-compose run mumble bash` then `ls -alih /data` (bash will bypass the entrypoint to give you a shell)

You can force docker to use a specific UID and GUID (https://github.com/mumble-voip/mumble-docker#using-a-different-uidgid) or use a volume (and not a mount point) to avoid right issues.

```
service:
    mumble-server:
        [....]
        volumes: mumble-server-data:/data

volumes:
    mumble-server-data:
```

**Reply by wliporace** [reply]
SO, I guess I'm totally lost and way over my head! My Docker is running in the Synology environment. I have not seen or been able to find ways to work from a terminal, access files to create my own install or how to edit the ini after the fact.  Not sure if you saw my compose from above.  Your example still does not seem to allow the files to be written to the area I would expect. 

I guess I could just let mumble to a basic install. I will just have a lot less control from what I can tell (still have no idea how to make changes). The other option may be for me to take a box and do a normal Linux install with or without docker.

**Reply by Krzmbrzl** [reply]
Maybe first try running the docker image in a regular environment and only move to something special once that is working as you expect it.

**Reply by wliporace** [reply]
Now that I have the latest imaged downloaded, I can create the container or stack. That has not been an issue. 
Then the issue is how do you manage the mumle server? 
Where are the config files?
I even went to the idea of adding an editor and could not figure how! 
From what I read, one was to create the stuff in an area you can see from the files portion of the Synology file system. 
I was able to do this with my RustDesk setup, works great! 

So I'm totally lost at this point.

**Reply by azlux** [reply]
Hoo, I just notice something,
You setup an external database for  your mumble.
In this case you don't need any volume. Just remove it.
Volume is to store the database and the config file. In you case the database is external, and the config is generated on-the-fly, so you don't need volume to store is permanently.

**Reply by wliporace** [reply]
So you're saying that I need to remove all of the volumes that I defined  
Leave them the way you already have defined (default scripting).  
I just need to set the usernames/passwords (I think). 

So then how do I do server administration?
How do I edit the ini (if needed).
I guess I'm still missing a piece of the puzzle.

**Reply by azlux** [reply]
The easy way for you to pilot the config file is with environment variables : https://github.com/mumble-voip/mumble-docker#configuration
I see into your docker-compose you already start this part.

The server administration is through the mumble client software, changes are done into the database.

**Reply by wliporace** [reply]
This is the error that I'm getting:
failed to deploy a stack: Network mumble-server_default Creating Network mumble-server_default Created Container postgres Creating Container postgres Created Container mumble-server Creating Container mumble-server Created Container mumble-mumo Creating Container mumble-mumo Created Container postgres Starting Error response from daemon: Bind mount failed: '/data/compose/data/postgres/data' does not exists

So, this is my docker compose:
version: "3"
services:
    mumble-server:
        image: mumblevoip/mumble-server
        container_name: mumble-server
        hostname: mumble-server
        restart: on-failure
        environment:
            MUMBLE_CONFIG_DATABASE: mumble
            MUMBLE_CONFIG_DB_DRIVER: QPSQL
            MUMBLE_CONFIG_DB_USERNAME: wc2l
            MUMBLE_CONFIG_DB_PASSWORD: JustadummyPassw0rd!
            MUMBLE_CONFIG_DB_HOST: postgres
            MUMBLE_CONFIG_DB_PORT: 5432
            MUMBLE_CONFIG_ICE: tcp -h 127.0.0.1 -p 6502
            MUMBLE_CONFIG_IMAGEMESSAGELENGTH: 1310720
            MUMBLE_CONFIG_REGISTERNAME: Main Channel Name
            MUMBLE_CONFIG_USERNAME: '[ -=\\w\\[\\]\\{\\}\\(\\)\\@\\|\\.]+'
            MUMBLE_CONFIG_CHANNELNAME: '[ \\-=\\w\\#\\[\\]\\{\\}\\(\\)\\@\\|\\%\\'']+'
            MUMBLE_CONFIG_WELCOMETEXT: 'Hello there !'
            MUMBLE_VERBOSE: 1
        ports:
            - 64738:64738
            - 64738:64738/udp
        depends_on:
            - postgres

    mumble-mumo:
        image: mumblevoip/mumo
        container_name: mumble-mumo
        restart: on-failure
        volumes:
            - ../data/mumo:/data
        network_mode : "service:mumble-server"
        depends_on:
            - mumble-server

    postgres:
        image: postgres:14
        container_name: postgres
        hostname: postgres
        restart: on-failure
        expose:
            - 5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: JustadummyPassw0rd!
        volumes:
            - ../data/postgres/data:/var/lib/postgresql/data

**Reply by azlux** [reply]
It's related to path, since you don't use volume but mount point :
> /data/compose/data/postgres/data not found.

You have requests to mount the folder : `../data/postgres/data` to I suppose you don't have the good path, maybe portainer working dir is : `/data/compose/volume1`

**Reply by wliporace** [reply]
So for me, the issue seems to be the postgres path.. 
Most of the time I get:
failed to deploy a stack: services must be a mapping

**Reply by azlux** [reply]
This look like a indent issue:
YAML is indentation dependent. 

```
services:
postgres:
```
should be :
```
services:
   postgres:
````

**Reply by wliporace** [reply]
Here is the docker compose being user. This looks correct in notepad++ and in portainer! 
```
services:
    mumble-server:
        image: mumblevoip/mumble-server
        container_name: mumble-server
        hostname: mumble-server
        restart: on-failure
        environment:
            MUMBLE_CONFIG_DATABASE: mumble
            MUMBLE_CONFIG_DB_DRIVER: QPSQL
            MUMBLE_CONFIG_DB_USERNAME: wc2l
            MUMBLE_CONFIG_DB_PASSWORD: pass0rd!!
            MUMBLE_CONFIG_DB_HOST: postgres
            MUMBLE_CONFIG_DB_PORT: 5432
            MUMBLE_CONFIG_ICE: tcp -h 127.0.0.1 -p 6502
            MUMBLE_CONFIG_IMAGEMESSAGELENGTH: 1310720
            MUMBLE_CONFIG_REGISTERNAME: Main Channel Name
            MUMBLE_CONFIG_USERNAME: '[ -=\\w\\[\\]\\{\\}\\(\\)\\@\\|\\.]+'
            MUMBLE_CONFIG_CHANNELNAME: '[ \\-=\\w\\#\\[\\]\\{\\}\\(\\)\\@\\|\\%\\'']+'
            MUMBLE_CONFIG_WELCOMETEXT: 'Hello there !'
            MUMBLE_VERBOSE: 1
        ports:
            - 64738:64738
            - 64738:64738/udp
        depends_on:
            - postgres

    mumble-mumo:
        image: mumblevoip/mumo
        container_name: mumble-mumo
        restart: on-failure
        volumes:
            - ../data/mumo:/data
        network_mode : "service:mumble-server"
        depends_on:
            - mumble-server

    postgres:
        image: postgres:14
        container_name: postgres
        hostname: postgres
        restart: on-failure
        expose:
            - 5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: passw0rd!!
        volumes:
            - ../data/postgres/data:/var/lib/postgresql/data
```

So messing with the paths, gives different answers, but know success. 
Bind mount failed: '/data/compose/postgres/data' does not exists
Bind mount failed: '/data/compose/data/compose/postgres/data' does not exists
Bind mount failed: '/data/compose/data/postgres/data' does not exists
Bind mount failed: '/data/compose/vol1/postgres/data' does not existss
Bind mount failed: '/data/compose/data/compose/volume1/postgres/data' does not exists

I know you understand. I was just testing to see if I could get it to work.
