### ISSUE TITLE
Podman: unable to open database file

### ISSUE THREAD

**Issue by krateng** [mumble-voip/mumble-docker#21]
Hi,

when I try to run mumble with podman 3.0.1 on Debian and mount the DB file (tested with full 777 permissions), I get

`ServerDB: Failed initialization: unable to open database file Error opening database`

This happens even when I just mount the empty folder and want Mumble to create its own DB file. Any ideas what causes this?

**Comment by Krzmbrzl** [comment]
Is that all that the logs have to say about this? 👀

**Comment by azlux** [comment]
Can you paste the full logs (anonymized of course) (or the config if you don't use the env variable) ?

**Comment by krateng** [comment]
There seem to be no logs generated in the specified directory. The console output is as follows:

```
Command used to start the mumble-server : /usr/bin/mumble-server -fg -ini /data/murmur.ini
<X>2022-03-22 22:02:48.131 SSL: OpenSSL version is 'OpenSSL 1.1.1l  24 Aug 2021'
<W>2022-03-22 22:02:48.131 Initializing settings from /data/murmur.ini (basepath /data)
<W>2022-03-22 22:02:48.463 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<F>2022-03-22 22:02:48.488 ServerDB: Failed initialization: unable to open database file Error opening database
exit code: 1
```

This is my configuration
```
services:
  mumble:
    container_name: mumble
    image: mumblevoip/mumble-server
    ports:
    - 64738:64738
    volumes:
    - $PWD/mumble/data:/data
    - $PWD/mumble/logs:/var/log
    restart: unless-stopped
```
