### ISSUE TITLE
All config environment variables are ignored

### ISSUE THREAD

**Issue by BorisBrock** [mumble-voip/mumble-docker#24]
I run the mumble server with this docker compose file:

```
services:
  murmur:
    container_name: murmur
    image: mumblevoip/mumble-server:latest
    restart: always
    ports:
      - "49155:50051/tcp"
      - "64738:64738/tcp"
      - "64738:64738/udp"
    environment:
      MUMBLE_CONFIG_SERVER_PASSWORD: "mypassword"
      MUMBLE_CONFIG_WELCOME_TEXT: "My Welcome Text"
      MUMBLE_CONFIG_USERS: "8"
      MUMBLE_CONFIG_BANDWIDTH: "128000"
```

None of the settings seem to work. E.g. the log file shows:

> Setting config "database" to: '/data/murmur.sqlite'
> Setting config "ice" to: '"tcp -h 127.0.0.1 -p 6502"'
> Setting config "welcometext" to: '"<br />Welcome to this server, running the official Mumble Docker image.<br />Enjoy your stay!<br />"'
> Setting config "port" to: '64738'
> Setting config "users" to: '100'
> Running Mumble server as uid=1000 gid=1000
> "/data" has the following permissions set:
>   drwxr-xr-x, owner: "mumble" (UID: 1000), group: "users" (GID: 100)
> Command run to start the service : /usr/bin/mumble-server -fg -ini /data/mumble_server_config.ini
> Starting...

As you can see the welcome text is not what was configured.

**Comment by Krzmbrzl** [comment]
@azlux do you have an idea? I don't have any experience with docker compose. 

@BorisBrock could you try running the container manually to see if the result remains the same?

**Comment by BorisBrock** [comment]
@Krzmbrzl Starting the container without Docker Compose actually works. In that case the environment variables are applied as expected.

**Comment by Krzmbrzl** [comment]
Interesting. In that case my suspicion would be that for some reason docker compose doesn't set the environment variables as expected :thinking:

**Comment by azlux** [comment]
@BorisBrock Do you find your ENV into the output of `docker inspect <container runn ID (can be found with docker ps | grep mumble)>`

**Comment by restitux** [comment]
Shouldn't the environment variable be `MUMBLE_CONFIG_WELCOMETEXT` not `MUMBLE_CONFIG_WELCOME_TEXT` (note the removed space)?

**Comment by Krzmbrzl** [comment]
Additional underscores in the variable names are ignored (see README)

**Comment by rastacalavera** [comment]
Hello,

I tried a modification of @BorisBrock and the welcome message works fine, but I had issues with a volume mount and default channels.

When I try to bring the container up, I get a permission error of:
```
2022-10-06T02:25:12.742473486Z /entrypoint.sh: line 77: /data/mumble_server_config.ini: Permission denied
2022-10-06T02:25:20.061774974Z /entrypoint.sh: line 77: /data/mumble_server_config.ini: Permission denied
```
My host user has the ID of 1000 and I even specified the PUID/GUID in the compose file but it still makes everything as root.

So then for testing, I `sudo chmod 777 data/mumble` and everything starts to work but there are no other channels than root.

My compose file is shown below:

```
services:
  murmur:
    container_name: murmur
    image: mumblevoip/mumble-server:latest
    restart: unless-stopped
    ports:
      - "49155:50051/tcp"
      - "64738:64738/tcp"
      - "64738:64738/udp"
    environment:
       MUMBLE_CONFIG_SERVER_PASSWORD: "mypassword"
       MUMBLE_CONFIG_WELCOME_TEXT: "Howdy Ya'll This is a Mumble Server"
       MUMBLE_CONFIG_USERS: "8"
       MUMBLE_CONFIG_BANDWIDTH: "128000"
       MUMBLE_CONFIG_channelname: "lobby"
       MUMBLE_CONFIG_channelname: "hello"
       MUMBLE_CONFIG_defaultchannel: "2"
       PUID: "1000"
       GUID: "1000"
    volumes:
      - "./data/mumble:/data:rw"
```
