### ISSUE TITLE
Remove PGID PUID Limitations

### ISSUE THREAD

**Issue by OdinVex** [mumble-voip/mumble-docker#34]
Broken bind mount access for Syn&QTS even with PGID=0, PUID=0,  MUMBLE_GID=0, MUMBLE_UID=0, /data:770 (normally 660) and owned (docker running under UID=0, GID=0, forced requirement). Why is every docker trying to force running as 1000:1000+ when you can let the end user do what they need? So much hand-holding...\*sigh\* Breaking usability.

```
/entrypoint.sh: line 77: /data/mumble_server_config.ini: Permission denied
```

**Comment by OdinVex** [comment]
Yes, I know I can build the Dockerfile. Why not just add a permissions correction into entrypoint to allow using PGID/PUID?

For now, I'm using this `compose`:

```
     command: |
      /bin/bash -c "groupmod -o -g 0 mumble; usermod -o -u 0 mumble; runuser mumble -g mumble -c '/entrypoint.sh /usr/bin/mumble-server -fg' 2>/dev/null"
    entrypoint: /bin/bash -c "/bin/bash -c \"$${@}\""
    environment:
      - PGID=0 # administrators
      - PUID=0 # admin
      - UMASK=000 # Leave permissions alone
    user: root # exec entrypoint as root (0:0) inside docker
```

It's to maintain share permissions correctly in Syn&QTS.

Edit: This was lazily put together, mind. The redundant shells were from tinkering and left over, I didn't bother to remove them.
