### ISSUE TITLE
mumble docker image error

### ISSUE THREAD

**Issue by sbodese** [mumble-voip/mumble-docker#39]
### Description

hi folks

the latest docker image 
mumblevoip/mumble-server:latest 
wont work

docker log says:

`exec /entrypoint.sh: exec format error`

### Steps to reproduce

run the current docker image

### Mumble version

mumblevoip/mumble-server:latest 

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
How exactly do you run the image?

**Comment by AlexPewMaster** [comment]
Hi, I'm also having this issue. The Docker container fails to start with the same error: `exec /entrypoint.sh: exec format error`

This is my `docker-compose.yaml` file:
```yaml
version: "3.3"
services:
  mumble-server:
    container_name: mumble-server
    ports:
      - 64738:64738/tcp
      - 64738:64738/udp
      - 6502:6502/tcp
    volumes:
      - ./data/mumble:/data
    restart: on-failure
    image: mumblevoip/mumble-server:latest
    environment:
      - ice="tcp -h 127.0.0.1 -p 6502"
      - icesecretwrite=**********
      - allowping=true
      - users=1000
      - rememberchannel=true
      - opusthreshold=0
      - registerName=**********
      - registerHostname=**********
networks: {}
```
*some information censored for privacy reasons* 

System Information:
**OS**: Raspberry Pi OS Lite / Debian 12
**Architecture**: arm64 / aarch64

I found this issue online, I don't know if that's relevant to this issue though: https://github.com/docker/compose/issues/10185
