### ISSUE TITLE
Murmur tries to recreate existing tables

### ISSUE THREAD

**Issue by Wobak** [mumble-voip/mumble-docker#59]
Hello,

My server went down because of hardware issue, so I'm migrating the data elsewhere.

When I got the docker compose up, my database was old, so I upgraded it using appropriate images and mariadb-upgrade commands.

Now that I'm on the latest available mariadb version, the server is restarting in loop with the following error : 

```
murmur  | Command run to start the service : /usr/bin/mumble-server -fg -v -ini /data/murmur.ini
murmur  | Starting...
murmur  | <X>2025-03-24 17:32:17.125 SSL: OpenSSL version is 'OpenSSL 3.0.13 30 Jan 2024'
murmur  | <W>2025-03-24 17:32:17.126 Initializing settings from /data/murmur.ini (basepath /data)
murmur  | <W>2025-03-24 17:32:17.126 Binding to address 0.0.0.0
murmur  | <W>2025-03-24 17:32:17.126 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
murmur  | <W>2025-03-24 17:32:17.278 Renaming old tables...
murmur  | <W>2025-03-24 17:32:17.294 Generating new tables...
murmur  | <F>2025-03-24 17:32:17.425 SQL Error [CREATE TABLE `murmur_channel_listeners` (`server_id` INTEGER NOT NULL, `user_id` INTEGER NOT NULL, `channel_id` INTEGER NOT NULL, `volume_adjustment` FLOAT DEFAULT 1, `enabled` SMALLINT DEFAULT 1)]: Table 'murmur_channel_listeners' already exists QMYSQL3: Unable to execute statement
```

Here is the docker compose (redacted of course) : 

```
services:
  murmur-db:
    image: lscr.io/linuxserver/mariadb
    container_name: "murmur-db"
    environment:
      - PUID=10000
      - PGID=10000
      - MYSQL_ROOT_PASSWORD=<redacted>
      - TZ=Europe/Paris
      - MYSQL_DATABASE=mumble
      - MYSQL_USER=mumble
      - MYSQL_PASSWORD=<redacted>
    volumes:
      - ./db:/config
    restart: unless-stopped
    networks:
      - mumble-internal

  murmur:
    user: "10000"
    image: mumblevoip/mumble-server:latest
    container_name: "murmur"
    restart: always
    environment:
      - MUMBLE_CUSTOM_CONFIG_FILE=/data/murmur.ini
      - MUMBLE_VERBOSE=true
    networks:
      - mumble
      - mumble-internal
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"
    volumes:
      - ./data:/data
      - ./mumble_server_config.ini:/data/murmur.ini
    depends_on:
      - murmur-db

networks:
  mumble-internal:
  mumble:
    external: true
```

Is there a way for me to tell murmur to use the tables instead of trying to recreate them?

Thanks,
