### ISSUE TITLE
Support non hardcoded secret names

### ISSUE THREAD

**Issue by mmathau** [mumble-voip/mumble-docker#60]
At the moment the way the `entrypoint.sh` file reads the docker / podman secrets at [L107](https://github.com/mumble-voip/mumble-docker/blob/8b2015be45684094658d5290fc8f3191ff0ea20c/entrypoint.sh#L107) for anything `MUMBLE_CONFIG_` related and [L155](https://github.com/mumble-voip/mumble-docker/blob/8b2015be45684094658d5290fc8f3191ff0ea20c/entrypoint.sh#L155) for the superuser password only allows secrets to be named exactly either `MUMBLE_CONFIG_*` or `MUMBLE_SUPERUSER_PASSWORD`.

This leads to a (working) example docker `compose.yml` file like the following:
```yml
services:
  mumble:
    image: mumblevoip/mumble-server:latest
    container_name: mumble
    hostname: mumble
    secrets:
      - MUMBLE_CONFIG_SERVER_PASSWORD
      - MUMBLE_SUPERUSER_PASSWORD
    environment:
      MUMBLE_CONFIG_SERVER_PASSWORD: /run/secrets/MUMBLE_CONFIG_SERVER_PASSWORD
      MUMBLE_SUPERUSER_PASSWORD: /run/secrets/MUMBLE_SUPERUSER_PASSWORD
    env_file:
      - mumble.env
    ports:
      - "64738:64738"
      - "64738:64738/udp"
    volumes:
      - mumble_data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - mumble
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cpus: "1.5"
    mem_limit: 2048m
    logging:
      driver: "journald"


secrets:
  MUMBLE_CONFIG_SERVER_PASSWORD:
    file: server_password.secret
  MUMBLE_SUPERUSER_PASSWORD:
    file: superuser_password.secret

volumes:
  mumble_data:
    name: mumble_data

networks:
  mumble:
    external: false
    name: mumble
```

It would be nice to change the way the entrypoint handles the secrets to allow non hardcoded names
